# repos.toml
# Workspace clones are materialized into ./deps/<name> (gitignored).
[[repo]]
name = "phys-pipeline"
url  = "https://github.com/phys-sims/phys-pipeline.git"
ref  = "main"

[[repo]]
name = "phys-sims-utils"
url  = "https://github.com/phys-sims/phys-sims-utils.git"
ref  = "main"

[[repo]]
name = "fiber-link-sim"
url  = "https://github.com/phys-sims/fiber-link-sim.git"
ref  = "main"

[[repo]]
name = "fiber-link-testbench"
url  = "https://github.com/phys-sims/fiber-link-testbench.git"
ref  = "main"

